//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMyName", ReplyAction="http://tempuri.org/IService/getMyNameResponse")]
        string getMyName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMyName", ReplyAction="http://tempuri.org/IService/getMyNameResponse")]
        System.Threading.Tasks.Task<string> getMyNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMyEmail", ReplyAction="http://tempuri.org/IService/getMyEmailResponse")]
        string getMyEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMyEmail", ReplyAction="http://tempuri.org/IService/getMyEmailResponse")]
        System.Threading.Tasks.Task<string> getMyEmailAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Consumer.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Consumer.ServiceReference1.IService>, Consumer.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMyName() {
            return base.Channel.getMyName();
        }
        
        public System.Threading.Tasks.Task<string> getMyNameAsync() {
            return base.Channel.getMyNameAsync();
        }
        
        public string getMyEmail() {
            return base.Channel.getMyEmail();
        }
        
        public System.Threading.Tasks.Task<string> getMyEmailAsync() {
            return base.Channel.getMyEmailAsync();
        }
    }
}
